"""remove phone from contacts

Revision ID: 0de60b6871de
Revises: f25b27344175
Create Date: 2026-07-04 13:53:23.438426+09:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0de60b6871de'
down_revision: Union[str, None] = 'f25b27344175'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contacts', 'user_id',
               existing_type=sa.INTEGER(),
               comment='문의 회원 FK — 탈퇴 시 SET NULL',
               existing_comment='문의 회원 FK — 비로그인 시 NULL',
               existing_nullable=True)
    op.drop_column('contacts', 'phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.alter_column('contacts', 'user_id',
               existing_type=sa.INTEGER(),
               comment='문의 회원 FK — 비로그인 시 NULL',
               existing_comment='문의 회원 FK — 탈퇴 시 SET NULL',
               existing_nullable=True)
    # ### end Alembic commands ###
