"""add product_model_name_snapshot to order_items

Revision ID: 1b7cb4efab36
Revises: 0de60b6871de
Create Date: 2026-07-06 01:09:11.507079+09:00

신규 컬럼 추가 후, 기존 로우는 products.model_name 으로 백필한다
(products 가 이미 삭제된 order_item 은 백필 대상에서 제외 — NULL 유지).
신규 주문은 order_service.create_order 에서 생성 시점에 자동으로 채워짐.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1b7cb4efab36'
down_revision: Union[str, None] = '0de60b6871de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('product_model_name_snapshot', sa.String(length=100), nullable=True, comment='주문 당시 모델명 (스냅샷). NULL 허용 — 모델명 미입력 상품 대응'))
    # ### end Alembic commands ###

    # 기존 로우 백필 — products.model_name 이 NULL 이면 그대로 NULL 유지
    op.execute(
        """
        UPDATE order_items
        SET product_model_name_snapshot = products.model_name
        FROM products
        WHERE order_items.product_id = products.id
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'product_model_name_snapshot')
    # ### end Alembic commands ###
