"""convert serial id columns to identity

Revision ID: 3509e1f6a778
Revises: fe0e26b92c26
Create Date: 2026-05-01 15:01:36.566612+09:00

"""
from typing import Sequence, Union

from alembic import op


revision: str = "3509e1f6a778"
down_revision: Union[str, None] = "fe0e26b92c26"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# 기존 init 마이그레이션이 plain Integer로 만들어 SERIAL이 붙은 10개 테이블.
# 모델은 Identity(always=False) 선언이라 드리프트 발생 → 진짜 IDENTITY로 통일.
TABLES: tuple[str, ...] = (
    "addresses",
    "cart_items",
    "identity_verifications",
    "order_items",
    "orders",
    "payments",
    "product_images",
    "products",
    "shipments",
    "users",
)


def upgrade() -> None:
    for table in TABLES:
        seq = f"{table}_id_seq"
        op.execute(
            f"""
DO $$
DECLARE
  v_next BIGINT;
BEGIN
  SELECT COALESCE(MAX(id), 0) + 1 INTO v_next FROM {table};
  ALTER TABLE {table} ALTER COLUMN id DROP DEFAULT;
  DROP SEQUENCE IF EXISTS {seq};
  EXECUTE format(
    'ALTER TABLE {table} ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH %s)',
    v_next
  );
END $$;
"""
        )


def downgrade() -> None:
    for table in TABLES:
        seq = f"{table}_id_seq"
        op.execute(
            f"""
DO $$
DECLARE
  v_next BIGINT;
BEGIN
  SELECT COALESCE(MAX(id), 0) + 1 INTO v_next FROM {table};
  ALTER TABLE {table} ALTER COLUMN id DROP IDENTITY IF EXISTS;
  EXECUTE format('CREATE SEQUENCE {seq} START WITH %s', v_next);
  ALTER SEQUENCE {seq} OWNED BY {table}.id;
  ALTER TABLE {table} ALTER COLUMN id SET DEFAULT nextval('{seq}'::regclass);
END $$;
"""
        )
