"""convert serial id columns to identity

Revision ID: 3509e1f6a778
Revises: fe0e26b92c26
Create Date: 2026-05-01 15:01:36.566612+09:00

"""
from typing import Sequence, Union

from alembic import op


revision: str = "3509e1f6a778"
down_revision: Union[str, None] = "fe0e26b92c26"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# 기존 init 마이그레이션이 plain Integer로 만들어 SERIAL이 붙은 10개 테이블.
# 모델은 Identity(always=False) 선언이라 드리프트 발생 → 진짜 IDENTITY로 통일.
TABLES: tuple[str, ...] = (
    "addresses",
    "cart_items",
    "identity_verifications",
    "order_items",
    "orders",
    "payments",
    "product_images",
    "products",
    "shipments",
    "users",
)


def upgrade() -> None:
    # init_schema가 이미 Identity(always=False)로 테이블을 만드는 환경(신규 DB)에서는
    # id 컬럼이 처음부터 IDENTITY라 여기서 다시 변환하면 "already an identity column" 에러가 남.
    # SERIAL(DEFAULT nextval)로 만들어졌던 기존 DB만 변환 대상으로 삼도록 이미 IDENTITY인 테이블은 건너뛴다.
    for table in TABLES:
        seq = f"{table}_id_seq"
        op.execute(
            f"""
DO $$
DECLARE
  v_next BIGINT;
  v_is_identity TEXT;
BEGIN
  SELECT is_identity INTO v_is_identity
  FROM information_schema.columns
  WHERE table_name = '{table}' AND column_name = 'id';

  IF v_is_identity = 'NO' THEN
    SELECT COALESCE(MAX(id), 0) + 1 INTO v_next FROM {table};
    ALTER TABLE {table} ALTER COLUMN id DROP DEFAULT;
    DROP SEQUENCE IF EXISTS {seq};
    EXECUTE format(
      'ALTER TABLE {table} ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH %s)',
      v_next
    );
  END IF;
END $$;
"""
        )


def downgrade() -> None:
    for table in TABLES:
        seq = f"{table}_id_seq"
        op.execute(
            f"""
DO $$
DECLARE
  v_next BIGINT;
  v_is_identity TEXT;
BEGIN
  SELECT is_identity INTO v_is_identity
  FROM information_schema.columns
  WHERE table_name = '{table}' AND column_name = 'id';

  IF v_is_identity = 'YES' THEN
    SELECT COALESCE(MAX(id), 0) + 1 INTO v_next FROM {table};
    ALTER TABLE {table} ALTER COLUMN id DROP IDENTITY IF EXISTS;
    EXECUTE format('CREATE SEQUENCE {seq} START WITH %s', v_next);
    ALTER SEQUENCE {seq} OWNED BY {table}.id;
    ALTER TABLE {table} ALTER COLUMN id SET DEFAULT nextval('{seq}'::regclass);
  END IF;
END $$;
"""
        )
