"""add_withdrawn_at_to_users

Revision ID: 4cfeaf4318f6
Revises: b427d8f8f268
Create Date: 2026-06-24 21:57:49.099813+09:00

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '4cfeaf4318f6'
down_revision: str | None = 'b427d8f8f268'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('withdrawn_at', sa.DateTime(timezone=True), nullable=True, comment='회원탈퇴 처리 시각. NULL 이면 활성 계정'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'withdrawn_at')
    # ### end Alembic commands ###
