"""본인인증 CI/DI 제거, Octomo 전화인증으로 대체

Revision ID: 6105137b8e93
Revises: 1b7cb4efab36
Create Date: 2026-07-12 08:24:23.861228+09:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '6105137b8e93'
down_revision: Union[str, None] = '1b7cb4efab36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 컬럼 통합(옵션 B): identity_verified_at 을 곧 삭제하므로, phone_verified_at 이
    # 비어있던 기존 사용자(과거 CI/DI 플로우로만 인증됐던 계정)에게 인증 이력이
    # 통째로 사라지지 않도록 값을 옮겨 담는다. drop 전에 반드시 먼저 실행.
    op.execute(
        """
        UPDATE users
        SET phone_verified_at = identity_verified_at
        WHERE phone_verified_at IS NULL AND identity_verified_at IS NOT NULL
        """
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_identity_verifications_user_id'), table_name='identity_verifications')
    op.drop_table('identity_verifications')
    op.alter_column('users', 'phone_verified_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='휴대폰 인증(Octomo) 통과 시각. NULL 이면 미인증 — User.verified 의 유일한 기준',
               existing_comment='SMS 인증 통과 시각. NULL 이면 미인증 상태',
               existing_nullable=True)
    op.drop_column('users', 'birth_date')
    op.drop_column('users', 'ci')
    op.drop_column('users', 'di')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'identity_verified_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('identity_verified_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='본인인증 완료 시각. NULL 이면 주문 진입 전 인증 강제'))
    op.add_column('users', sa.Column('gender', sa.VARCHAR(length=10), autoincrement=False, nullable=True, comment='본인인증 결과 저장. 통계 외 용도로 사용 금지'))
    op.add_column('users', sa.Column('di', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='Duplicate Information(64B). 동일 사이트 중복 가입 차단용 — 암호화 저장'))
    op.add_column('users', sa.Column('ci', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='Connecting Information(88B). 동일인 식별용 — 암호화 저장 필수'))
    op.add_column('users', sa.Column('birth_date', sa.DATE(), autoincrement=False, nullable=True, comment='본인인증 결과 저장. 만 14세 미만 차단 판정에 사용'))
    op.alter_column('users', 'phone_verified_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='SMS 인증 통과 시각. NULL 이면 미인증 상태',
               existing_comment='휴대폰 인증(Octomo) 통과 시각. NULL 이면 미인증 — User.verified 의 유일한 기준',
               existing_nullable=True)
    op.create_table('identity_verifications',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False, comment='인증 시도 PK'),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='인증 시도 사용자 FK'),
    sa.Column('provider', sa.VARCHAR(length=20), autoincrement=False, nullable=False, comment='인증 PG (TOSS/NICE/KCB)'),
    sa.Column('result', sa.VARCHAR(length=10), autoincrement=False, nullable=False, comment='인증 결과 (SUCCESS/FAIL)'),
    sa.Column('request_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='PG 요청 식별자. 콜백 멱등성 보장 키 — 유니크 인덱스 추가 검토'),
    sa.Column('verified_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='SUCCESS 시점. FAIL 이면 NULL'),
    sa.Column('fail_reason', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='FAIL 사유 (PG 에러 메시지). 사용자 노출 전 정제 필요'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='레코드 최초 생성 시각 (UTC, DB 기본값으로 자동 채움)'),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='마지막 수정 시각 (UPDATE 시 자동 갱신)'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('identity_verifications_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('identity_verifications_pkey'))
    )
    op.create_index(op.f('ix_identity_verifications_user_id'), 'identity_verifications', ['user_id'], unique=False)
    # ### end Alembic commands ###
