"""add product_image label and order_item image snapshot

Revision ID: 6ae8f19a3e0f
Revises: 3509e1f6a778
Create Date: 2026-05-01 15:08:16.992713+09:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6ae8f19a3e0f'
down_revision: Union[str, None] = '3509e1f6a778'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('product_image_url_snapshot', sa.String(length=500), nullable=True))
    op.add_column('product_images', sa.Column('label', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_images', 'label')
    op.drop_column('order_items', 'product_image_url_snapshot')
    # ### end Alembic commands ###
