"""add_user_status_enum

Revision ID: 7e4bbdf7f10f
Revises: e1e85745b3c8
Create Date: 2026-06-22 13:41:11.429310+09:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7e4bbdf7f10f'
down_revision: Union[str, None] = 'e1e85745b3c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('status', sa.Enum('ACTIVE', 'BANNED', 'DORMANT', name='userstatus', native_enum=False, length=20), server_default='ACTIVE', nullable=False, comment='계정 상태. BANNED → 로그인 차단. is_active 와 동기화 유지'))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='활성 여부. status=ACTIVE ↔ is_active=True 로 동기화',
               existing_comment='활성 여부. UserStatus(ACTIVE/BANNED/DORMANT) 도입 시 일원화 예정',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='활성 여부. UserStatus(ACTIVE/BANNED/DORMANT) 도입 시 일원화 예정',
               existing_comment='활성 여부. status=ACTIVE ↔ is_active=True 로 동기화',
               existing_nullable=False)
    op.drop_column('users', 'status')
    # ### end Alembic commands ###
