"""add_help_module_notices_faqs_contacts

Revision ID: 9855aeca0293
Revises: ee1a45f3a6b2
Create Date: 2026-07-02 18:09:33.453239+09:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9855aeca0293'
down_revision: Union[str, None] = 'ee1a45f3a6b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faqs',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False, comment='카테고리 (예: 주문, 배송, 결제, 회원, 기타)'),
    sa.Column('question', sa.String(length=300), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='카테고리 내 노출 순서 (오름차순)'),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='레코드 최초 생성 시각 (UTC, DB 기본값으로 자동 채움)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='마지막 수정 시각 (UPDATE 시 자동 갱신)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faqs_category'), 'faqs', ['category'], unique=False)
    op.create_table('notices',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False, comment='상단 고정 여부'),
    sa.Column('is_published', sa.Boolean(), nullable=False, comment='게시 여부 (False=비공개)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='레코드 최초 생성 시각 (UTC, DB 기본값으로 자동 채움)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='마지막 수정 시각 (UPDATE 시 자동 갱신)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='문의 회원 FK — 비로그인 시 NULL'),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False, comment='답변 수신 이메일'),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ANSWERED', name='contact_status'), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True, comment='답변 완료 시각'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='레코드 최초 생성 시각 (UTC, DB 기본값으로 자동 채움)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='마지막 수정 시각 (UPDATE 시 자동 갱신)'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_user_id'), 'contacts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contacts_user_id'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_table('notices')
    op.drop_index(op.f('ix_faqs_category'), table_name='faqs')
    op.drop_table('faqs')
    # ### end Alembic commands ###
