"""dynamic_category_varchar_add_icon

Revision ID: b427d8f8f268
Revises: 7e4bbdf7f10f
Create Date: 2026-06-23 13:04:54.979794+09:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b427d8f8f268'
down_revision: Union[str, None] = '7e4bbdf7f10f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_categories',
    sa.Column('id', sa.String(length=30), nullable=False, comment='카테고리 식별자 (REFRIGERATOR 등 대문자+언더스코어)'),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='레코드 최초 생성 시각 (UTC, DB 기본값으로 자동 채움)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='마지막 수정 시각 (UPDATE 시 자동 갱신)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('products', 'category',
               existing_type=sa.VARCHAR(length=30),
               comment='대분류 ID. product_categories.id 를 FK 없이 참조 (유연성 우선)',
               existing_comment='대분류. 카테고리 칩 필터링과 인덱스 검색에 사용',
               existing_nullable=False)
    # ### end Alembic commands ###

    # 초기 카테고리 시드
    op.bulk_insert(
        sa.table(
            'product_categories',
            sa.column('id', sa.String),
            sa.column('title', sa.String),
            sa.column('icon', sa.String),
            sa.column('sort_order', sa.Integer),
        ),
        [
            {'id': 'REFRIGERATOR',    'title': '냉장고',    'icon': 'fridge',     'sort_order': 1},
            {'id': 'WASHING_MACHINE', 'title': '세탁기',    'icon': 'washer',     'sort_order': 2},
            {'id': 'TV',              'title': 'TV',        'icon': 'tv',         'sort_order': 3},
            {'id': 'AIR_CONDITIONER', 'title': '에어컨',    'icon': 'aircon',     'sort_order': 4},
            {'id': 'KITCHEN',         'title': '주방가전',  'icon': 'microwave',  'sort_order': 5},
            {'id': 'ETC',             'title': '기타',      'icon': 'menu',       'sort_order': 99},
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'category',
               existing_type=sa.VARCHAR(length=30),
               comment='대분류. 카테고리 칩 필터링과 인덱스 검색에 사용',
               existing_comment='대분류 ID. product_categories.id 를 FK 없이 참조 (유연성 우선)',
               existing_nullable=False)
    op.drop_table('product_categories')
    # ### end Alembic commands ###
