"""add label and memo to addresses

Revision ID: d958aba2670e
Revises: 4cfeaf4318f6
Create Date: 2026-06-28 09:45:36.322931+09:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd958aba2670e'
down_revision: Union[str, None] = '4cfeaf4318f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('label', sa.String(length=30), nullable=True, comment='배송지 별칭 (예: 집, 회사)'))
    op.add_column('addresses', sa.Column('memo', sa.String(length=200), nullable=True, comment='배송 메모 (예: 경비실 앞 놔주세요)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('addresses', 'memo')
    op.drop_column('addresses', 'label')
    # ### end Alembic commands ###
