"""add_favorites_table

Revision ID: e1e85745b3c8
Revises: 3304d5b557c6
Create Date: 2026-06-20 15:25:36.394225+09:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'e1e85745b3c8'
down_revision: Union[str, None] = '3304d5b557c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('user_id', sa.Integer(), nullable=False, comment='소유 사용자 FK. 탈퇴 시 cascade 삭제'),
    sa.Column('product_id', sa.Integer(), nullable=False, comment='관심 상품 FK. 상품 삭제 시 cascade 삭제'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='레코드 최초 생성 시각 (UTC, DB 기본값으로 자동 채움)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='마지막 수정 시각 (UPDATE 시 자동 갱신)'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'product_id')
    )
    op.alter_column('addresses', 'id',
               existing_type=sa.INTEGER(),
               comment='배송지 PK',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1))
    op.alter_column('addresses', 'user_id',
               existing_type=sa.INTEGER(),
               comment='소유 사용자 FK (회원 탈퇴 시 cascade 삭제)',
               existing_nullable=False)
    op.alter_column('addresses', 'recipient',
               existing_type=sa.VARCHAR(length=50),
               comment='수령인 이름',
               existing_nullable=False)
    op.alter_column('addresses', 'phone',
               existing_type=sa.VARCHAR(length=20),
               comment='수령인 연락처 (배송 안내용)',
               existing_nullable=False)
    op.alter_column('addresses', 'zipcode',
               existing_type=sa.VARCHAR(length=10),
               comment='우편번호 5자리 (직배송 가능 지역 판정에 사용)',
               existing_nullable=False)
    op.alter_column('addresses', 'address1',
               existing_type=sa.VARCHAR(length=255),
               comment='기본 주소 (도로명/지번)',
               existing_nullable=False)
    op.alter_column('addresses', 'address2',
               existing_type=sa.VARCHAR(length=255),
               comment='상세 주소 (동·호수 등)',
               existing_nullable=True)
    op.alter_column('addresses', 'is_default',
               existing_type=sa.BOOLEAN(),
               comment='기본 배송지 여부 — 사용자별 1건만 true 가 되도록 서비스 레이어에서 보장',
               existing_nullable=False)
    op.alter_column('addresses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='레코드 최초 생성 시각 (UTC, DB 기본값으로 자동 채움)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('addresses', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='마지막 수정 시각 (UPDATE 시 자동 갱신)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('cart_items', 'id',
               existing_type=sa.INTEGER(),
               comment='장바구니 항목 PK',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1))
    op.alter_column('cart_items', 'user_id',
               existing_type=sa.INTEGER(),
               comment='소유 사용자 FK. 탈퇴 시 cascade 정리',
               existing_nullable=False)
    op.alter_column('cart_items', 'product_id',
               existing_type=sa.INTEGER(),
               comment='담긴 상품 FK. 상품 삭제 시 cascade 로 함께 제거',
               existing_nullable=False)
    op.alter_column('cart_items', 'quantity',
               existing_type=sa.INTEGER(),
               comment='수량. 가전은 보통 1 이지만 동일 모델 다수 담기 허용',
               existing_nullable=False)
    op.alter_column('cart_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='레코드 최초 생성 시각 (UTC, DB 기본값으로 자동 채움)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('cart_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='마지막 수정 시각 (UPDATE 시 자동 갱신)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('identity_verifications', 'id',
               existing_type=sa.INTEGER(),
               comment='인증 시도 PK',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1))
    op.alter_column('identity_verifications', 'user_id',
               existing_type=sa.INTEGER(),
               comment='인증 시도 사용자 FK',
               existing_nullable=False)
    op.alter_column('identity_verifications', 'provider',
               existing_type=sa.VARCHAR(length=20),
               comment='인증 PG (TOSS/NICE/KCB)',
               existing_nullable=False)
    op.alter_column('identity_verifications', 'result',
               existing_type=sa.VARCHAR(length=10),
               comment='인증 결과 (SUCCESS/FAIL)',
               existing_nullable=False)
    op.alter_column('identity_verifications', 'request_id',
               existing_type=sa.VARCHAR(length=100),
               comment='PG 요청 식별자. 콜백 멱등성 보장 키 — 유니크 인덱스 추가 검토',
               existing_nullable=True)
    op.alter_column('identity_verifications', 'verified_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='SUCCESS 시점. FAIL 이면 NULL',
               existing_nullable=True)
    op.alter_column('identity_verifications', 'fail_reason',
               existing_type=sa.VARCHAR(length=255),
               comment='FAIL 사유 (PG 에러 메시지). 사용자 노출 전 정제 필요',
               existing_nullable=True)
    op.alter_column('identity_verifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='레코드 최초 생성 시각 (UTC, DB 기본값으로 자동 채움)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('identity_verifications', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='마지막 수정 시각 (UPDATE 시 자동 갱신)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('order_items', 'id',
               existing_type=sa.INTEGER(),
               comment='주문 라인 PK',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1))
    op.alter_column('order_items', 'order_id',
               existing_type=sa.INTEGER(),
               comment='소속 주문 FK',
               existing_nullable=False)
    op.alter_column('order_items', 'product_id',
               existing_type=sa.INTEGER(),
               comment='원본 상품 FK. RESTRICT — 주문이 있는 상품은 삭제 차단',
               existing_nullable=False)
    op.alter_column('order_items', 'product_title_snapshot',
               existing_type=sa.VARCHAR(length=200),
               comment='주문 당시 상품명 (스냅샷)',
               existing_nullable=False)
    op.alter_column('order_items', 'product_image_url_snapshot',
               existing_type=sa.VARCHAR(length=500),
               comment='주문 당시 대표 이미지 URL (스냅샷). 주문내역/마이페이지 카드에 노출',
               existing_nullable=True)
    op.alter_column('order_items', 'price_snapshot',
               existing_type=sa.INTEGER(),
               comment='주문 당시 판매가 (스냅샷). 가격 변동 후에도 결제 금액 재현 가능',
               existing_nullable=False)
    op.alter_column('order_items', 'quantity',
               existing_type=sa.INTEGER(),
               comment='주문 수량',
               existing_nullable=False)
    op.alter_column('orders', 'id',
               existing_type=sa.INTEGER(),
               comment='주문 PK (내부용)',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1))
    op.alter_column('orders', 'order_number',
               existing_type=sa.VARCHAR(length=32),
               comment='사람이 읽는 주문번호 (RK-YYMMDD####). 영수증/CS 식별자',
               existing_nullable=False)
    op.alter_column('orders', 'user_id',
               existing_type=sa.INTEGER(),
               comment='주문자 FK. 거래 정보 보존(5년) 의무로 RESTRICT — 회원 탈퇴 시에도 주문은 남김',
               existing_nullable=False)
    op.alter_column('orders', 'total_amount',
               existing_type=sa.INTEGER(),
               comment='최종 결제 금액(원) = 상품합 + 배송비 - 할인',
               existing_nullable=False)
    op.alter_column('orders', 'shipping_fee',
               existing_type=sa.INTEGER(),
               comment='배송비(원). 화물 60,000 / 직배송 40,000 / 일반택배는 무게 기반',
               existing_nullable=False)
    op.alter_column('orders', 'discount_amount',
               existing_type=sa.INTEGER(),
               comment='할인 금액(원). 직배송 선택 시 -20,000 등',
               existing_nullable=False)
    op.alter_column('orders', 'shipping_method',
               existing_type=sa.VARCHAR(length=20),
               comment='배송 방식. DIRECT 는 zipcode 가 서울/경기 prefix 일 때만 허용',
               existing_nullable=False)
    op.alter_column('orders', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='주문 상태. 관리자 탭 카운트와 사용자 마이페이지 카운트의 기준',
               existing_nullable=False)
    op.alter_column('orders', 'recipient_name',
               existing_type=sa.VARCHAR(length=50),
               comment='수령인 이름 (스냅샷)',
               existing_nullable=False)
    op.alter_column('orders', 'recipient_phone',
               existing_type=sa.VARCHAR(length=20),
               comment='수령인 연락처 (스냅샷)',
               existing_nullable=False)
    op.alter_column('orders', 'zipcode',
               existing_type=sa.VARCHAR(length=10),
               comment='우편번호 (스냅샷)',
               existing_nullable=False)
    op.alter_column('orders', 'address1',
               existing_type=sa.VARCHAR(length=255),
               comment='기본 주소 (스냅샷)',
               existing_nullable=False)
    op.alter_column('orders', 'address2',
               existing_type=sa.VARCHAR(length=255),
               comment='상세 주소 (스냅샷)',
               existing_nullable=True)
    op.alter_column('orders', 'memo',
               existing_type=sa.VARCHAR(length=500),
               comment='배송 메모 (예: 부재 시 경비실)',
               existing_nullable=True)
    op.alter_column('orders', 'paid_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='결제 완료 시각. PAID 전환 시 채움',
               existing_nullable=True)
    op.alter_column('orders', 'cancelled_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='취소 시각. CANCELLED/REFUNDED 전환 시 채움',
               existing_nullable=True)
    op.alter_column('orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='레코드 최초 생성 시각 (UTC, DB 기본값으로 자동 채움)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('orders', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='마지막 수정 시각 (UPDATE 시 자동 갱신)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('payments', 'id',
               existing_type=sa.INTEGER(),
               comment='결제 PK',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1))
    op.alter_column('payments', 'order_id',
               existing_type=sa.INTEGER(),
               comment='결제 대상 주문 FK. 결제가 있는 주문은 삭제 차단',
               existing_nullable=False)
    op.alter_column('payments', 'pg_provider',
               existing_type=sa.VARCHAR(length=20),
               comment='결제 PG (TOSS/KAKAO/NAVER)',
               existing_nullable=False)
    op.alter_column('payments', 'pg_tid',
               existing_type=sa.VARCHAR(length=100),
               comment='PG 거래 ID. 멱등성 키 — webhook 중복 호출 방어용 unique 제약',
               existing_nullable=True)
    op.alter_column('payments', 'method',
               existing_type=sa.VARCHAR(length=20),
               comment='결제 수단 (CARD/BANK/KAKAO_PAY/NAVER_PAY/TOSS_PAY)',
               existing_nullable=False)
    op.alter_column('payments', 'amount',
               existing_type=sa.INTEGER(),
               comment='결제 금액(원). Order.total_amount 와 일치해야 함',
               existing_nullable=False)
    op.alter_column('payments', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='결제 상태. webhook 처리의 멱등성 기준',
               existing_nullable=False)
    op.alter_column('payments', 'paid_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='PG 승인 시각',
               existing_nullable=True)
    op.alter_column('payments', 'cancelled_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='취소/환불 시각',
               existing_nullable=True)
    op.alter_column('payments', 'fail_reason',
               existing_type=sa.VARCHAR(length=500),
               comment='실패 사유 (PG 에러 메시지). 사용자 노출 전 정제 필요',
               existing_nullable=True)
    op.alter_column('payments', 'card_company',
               existing_type=sa.VARCHAR(length=30),
               comment="카드 발급사 (예: '신한카드'). 영수증 표시용 — PCI-DSS 안전",
               existing_nullable=True)
    op.alter_column('payments', 'card_last4',
               existing_type=sa.VARCHAR(length=4),
               comment='카드 끝 4자리. PCI-DSS 가 명시 허용 (first6+last4 까지 OK)',
               existing_nullable=True)
    op.alter_column('payments', 'installment_months',
               existing_type=sa.INTEGER(),
               comment='할부 개월 (0=일시불, 2~12=할부)',
               existing_nullable=True)
    op.alter_column('payments', 'approval_number',
               existing_type=sa.VARCHAR(length=50),
               comment='카드 승인번호. 환불/취소 호출 시 PG 가 요구',
               existing_nullable=True)
    op.alter_column('payments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='레코드 최초 생성 시각 (UTC, DB 기본값으로 자동 채움)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('payments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='마지막 수정 시각 (UPDATE 시 자동 갱신)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('product_images', 'id',
               existing_type=sa.INTEGER(),
               comment='이미지 PK',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1))
    op.alter_column('product_images', 'product_id',
               existing_type=sa.INTEGER(),
               comment='소유 상품 FK (상품 삭제 시 cascade)',
               existing_nullable=False)
    op.alter_column('product_images', 'url',
               existing_type=sa.VARCHAR(length=500),
               comment='S3 객체 URL (uploads/confirm 통과한 키만 허용)',
               existing_nullable=False)
    op.alter_column('product_images', 'sort_order',
               existing_type=sa.INTEGER(),
               comment='갤러리 정렬 순서 (0 부터 오름차순). 0 번이 카드 썸네일',
               existing_nullable=False)
    op.alter_column('product_images', 'label',
               existing_type=sa.VARCHAR(length=20),
               comment='이미지 라벨 (정면/측면/흠집 등). NULL 허용이지만 등급 B/C 는 흠집 권장',
               existing_nullable=True)
    op.alter_column('products', 'id',
               existing_type=sa.INTEGER(),
               comment='상품 PK',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1))
    op.alter_column('products', 'title',
               existing_type=sa.VARCHAR(length=200),
               comment='상품명. 카드/검색 노출용 — 브랜드+모델+용량 포함 권장',
               existing_nullable=False)
    op.alter_column('products', 'description',
               existing_type=sa.TEXT(),
               comment='상세 설명 (플레인 텍스트). 마크다운/HTML 은 서비스 레이어에서 sanitize',
               existing_nullable=False)
    op.alter_column('products', 'category',
               existing_type=sa.VARCHAR(length=30),
               comment='대분류. 카테고리 칩 필터링과 인덱스 검색에 사용',
               existing_nullable=False)
    op.alter_column('products', 'brand',
               existing_type=sa.VARCHAR(length=100),
               comment='브랜드명 (삼성/LG 등). 카드의 메타라인에 노출',
               existing_nullable=True)
    op.alter_column('products', 'model_name',
               existing_type=sa.VARCHAR(length=100),
               comment='모델명 (RT38K5982SL 등). 검색/AS 식별용',
               existing_nullable=True)
    op.alter_column('products', 'year_estimate',
               existing_type=sa.INTEGER(),
               comment='추정 연식 (yyyy). 철거 가전 특성상 정확한 제조연도가 없어 추정값',
               existing_nullable=True)
    op.alter_column('products', 'condition_grade',
               existing_type=sa.VARCHAR(length=5),
               comment='상태 등급 A/B/C. 등급별 컬러 뱃지로 시각화',
               existing_nullable=False)
    op.alter_column('products', 'warranty_works',
               existing_type=sa.BOOLEAN(),
               comment="동작 보증 여부. true 면 카드/상세에 '동작보증' 뱃지 노출",
               existing_nullable=False)
    op.alter_column('products', 'price',
               existing_type=sa.INTEGER(),
               comment='판매가 (원). 통화는 KRW 고정',
               existing_nullable=False)
    op.alter_column('products', 'original_price',
               existing_type=sa.INTEGER(),
               comment='원가/정가 (원). 할인율 계산 기준 — NULL 이면 할인 표기 생략',
               existing_nullable=True)
    op.alter_column('products', 'weight_kg',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='제품 무게(kg). 누적 절약 무게 집계와 배송비 산정에 사용',
               existing_nullable=True)
    op.alter_column('products', 'width_cm',
               existing_type=sa.INTEGER(),
               comment='가로 (cm)',
               existing_nullable=True)
    op.alter_column('products', 'depth_cm',
               existing_type=sa.INTEGER(),
               comment='깊이 (cm)',
               existing_nullable=True)
    op.alter_column('products', 'height_cm',
               existing_type=sa.INTEGER(),
               comment='높이 (cm)',
               existing_nullable=True)
    op.alter_column('products', 'stock',
               existing_type=sa.INTEGER(),
               comment='재고 수량. 보통 1개씩이지만 동일 모델 다수 입고 가능',
               existing_nullable=False)
    op.alter_column('products', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='노출 상태. 목록 API 는 ACTIVE 만 조회',
               existing_nullable=False)
    op.alter_column('products', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='레코드 최초 생성 시각 (UTC, DB 기본값으로 자동 채움)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('products', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='마지막 수정 시각 (UPDATE 시 자동 갱신)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('shipments', 'id',
               existing_type=sa.INTEGER(),
               comment='배송 PK',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1))
    op.alter_column('shipments', 'order_id',
               existing_type=sa.INTEGER(),
               comment='주문 FK (1:1). 주문 삭제 시 cascade',
               existing_nullable=False)
    op.alter_column('shipments', 'method',
               existing_type=sa.VARCHAR(length=20),
               comment='배송 방식. Order.shipping_method 와 동기화 유지',
               existing_nullable=False)
    op.alter_column('shipments', 'carrier',
               existing_type=sa.VARCHAR(length=50),
               comment='택배사명 (CJ대한통운, 한진택배 등). DIRECT 면 NULL',
               existing_nullable=True)
    op.alter_column('shipments', 'tracking_number',
               existing_type=sa.VARCHAR(length=50),
               comment='송장번호. 입력 시 IN_TRANSIT 자동 전환 트리거. DIRECT 면 NULL',
               existing_nullable=True)
    op.alter_column('shipments', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='배송 상태. 추적 API 폴링 결과로 DELIVERED 갱신',
               existing_nullable=False)
    op.alter_column('shipments', 'shipped_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='발송(IN_TRANSIT 전환) 시각',
               existing_nullable=True)
    op.alter_column('shipments', 'delivered_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='수령 시각. 환불 윈도우(7일) 계산 기준',
               existing_nullable=True)
    op.alter_column('shipments', 'last_tracked_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='배송 추적 API 마지막 폴링 시각. Redis 캐시 무효화 기준',
               existing_nullable=True)
    op.alter_column('shipments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='레코드 최초 생성 시각 (UTC, DB 기본값으로 자동 채움)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('shipments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='마지막 수정 시각 (UPDATE 시 자동 갱신)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('social_accounts', 'social_id',
               existing_type=sa.VARCHAR(length=100),
               comment='소셜 PG 의 사용자 ID (카카오는 long, 네이버는 string — 모두 string 으로 저장)',
               existing_comment='소셜 PG 의 사용자 ID (모두 string 으로 저장)',
               existing_nullable=False)
    op.alter_column('social_accounts', 'email_at_link',
               existing_type=sa.VARCHAR(length=255),
               comment='연결 시점에 PG 가 알려준 이메일 (감사용 스냅샷). 사용자가 PG 측에서 변경해도 이 값은 고정',
               existing_comment='연결 시점 PG 가 알려준 이메일 (감사용 스냅샷)',
               existing_nullable=True)
    op.alter_column('social_accounts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='레코드 최초 생성 시각 (UTC, DB 기본값으로 자동 채움)',
               existing_comment='레코드 최초 생성 시각 (UTC)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               comment='사용자 PK',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment='이메일. 비번찾기 등 본인확인용. 소문자 정규화는 서비스 레이어에서',
               existing_nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               comment='bcrypt 해시값. 평문/SHA 류는 절대 저장 금지',
               existing_nullable=False)
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=20),
               comment='휴대폰 번호 (하이픈 제거 정규화). SMS 인증 후에만 신뢰 가능',
               existing_nullable=True)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=20),
               comment='권한 등급 (USER/ADMIN). 관리자 API 가드의 기준',
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='활성 여부. UserStatus(ACTIVE/BANNED/DORMANT) 도입 시 일원화 예정',
               existing_nullable=False)
    op.alter_column('users', 'phone_verified_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='SMS 인증 통과 시각. NULL 이면 미인증 상태',
               existing_nullable=True)
    op.alter_column('users', 'identity_verified_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='본인인증 완료 시각. NULL 이면 주문 진입 전 인증 강제',
               existing_nullable=True)
    op.alter_column('users', 'ci',
               existing_type=sa.VARCHAR(length=255),
               comment='Connecting Information(88B). 동일인 식별용 — 암호화 저장 필수',
               existing_nullable=True)
    op.alter_column('users', 'di',
               existing_type=sa.VARCHAR(length=255),
               comment='Duplicate Information(64B). 동일 사이트 중복 가입 차단용 — 암호화 저장',
               existing_nullable=True)
    op.alter_column('users', 'birth_date',
               existing_type=sa.DATE(),
               comment='본인인증 결과 저장. 만 14세 미만 차단 판정에 사용',
               existing_nullable=True)
    op.alter_column('users', 'gender',
               existing_type=sa.VARCHAR(length=10),
               comment='본인인증 결과 저장. 통계 외 용도로 사용 금지',
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='레코드 최초 생성 시각 (UTC, DB 기본값으로 자동 채움)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='마지막 수정 시각 (UPDATE 시 자동 갱신)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='마지막 수정 시각 (UPDATE 시 자동 갱신)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='레코드 최초 생성 시각 (UTC, DB 기본값으로 자동 채움)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'gender',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='본인인증 결과 저장. 통계 외 용도로 사용 금지',
               existing_nullable=True)
    op.alter_column('users', 'birth_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='본인인증 결과 저장. 만 14세 미만 차단 판정에 사용',
               existing_nullable=True)
    op.alter_column('users', 'di',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Duplicate Information(64B). 동일 사이트 중복 가입 차단용 — 암호화 저장',
               existing_nullable=True)
    op.alter_column('users', 'ci',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Connecting Information(88B). 동일인 식별용 — 암호화 저장 필수',
               existing_nullable=True)
    op.alter_column('users', 'identity_verified_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='본인인증 완료 시각. NULL 이면 주문 진입 전 인증 강제',
               existing_nullable=True)
    op.alter_column('users', 'phone_verified_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='SMS 인증 통과 시각. NULL 이면 미인증 상태',
               existing_nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='활성 여부. UserStatus(ACTIVE/BANNED/DORMANT) 도입 시 일원화 예정',
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='권한 등급 (USER/ADMIN). 관리자 API 가드의 기준',
               existing_nullable=False)
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='휴대폰 번호 (하이픈 제거 정규화). SMS 인증 후에만 신뢰 가능',
               existing_nullable=True)
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='bcrypt 해시값. 평문/SHA 류는 절대 저장 금지',
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='이메일. 비번찾기 등 본인확인용. 소문자 정규화는 서비스 레이어에서',
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='사용자 PK',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1))
    op.alter_column('social_accounts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='레코드 최초 생성 시각 (UTC)',
               existing_comment='레코드 최초 생성 시각 (UTC, DB 기본값으로 자동 채움)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('social_accounts', 'email_at_link',
               existing_type=sa.VARCHAR(length=255),
               comment='연결 시점 PG 가 알려준 이메일 (감사용 스냅샷)',
               existing_comment='연결 시점에 PG 가 알려준 이메일 (감사용 스냅샷). 사용자가 PG 측에서 변경해도 이 값은 고정',
               existing_nullable=True)
    op.alter_column('social_accounts', 'social_id',
               existing_type=sa.VARCHAR(length=100),
               comment='소셜 PG 의 사용자 ID (모두 string 으로 저장)',
               existing_comment='소셜 PG 의 사용자 ID (카카오는 long, 네이버는 string — 모두 string 으로 저장)',
               existing_nullable=False)
    op.alter_column('shipments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='마지막 수정 시각 (UPDATE 시 자동 갱신)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('shipments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='레코드 최초 생성 시각 (UTC, DB 기본값으로 자동 채움)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('shipments', 'last_tracked_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='배송 추적 API 마지막 폴링 시각. Redis 캐시 무효화 기준',
               existing_nullable=True)
    op.alter_column('shipments', 'delivered_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='수령 시각. 환불 윈도우(7일) 계산 기준',
               existing_nullable=True)
    op.alter_column('shipments', 'shipped_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='발송(IN_TRANSIT 전환) 시각',
               existing_nullable=True)
    op.alter_column('shipments', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='배송 상태. 추적 API 폴링 결과로 DELIVERED 갱신',
               existing_nullable=False)
    op.alter_column('shipments', 'tracking_number',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='송장번호. 입력 시 IN_TRANSIT 자동 전환 트리거. DIRECT 면 NULL',
               existing_nullable=True)
    op.alter_column('shipments', 'carrier',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='택배사명 (CJ대한통운, 한진택배 등). DIRECT 면 NULL',
               existing_nullable=True)
    op.alter_column('shipments', 'method',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='배송 방식. Order.shipping_method 와 동기화 유지',
               existing_nullable=False)
    op.alter_column('shipments', 'order_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='주문 FK (1:1). 주문 삭제 시 cascade',
               existing_nullable=False)
    op.alter_column('shipments', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='배송 PK',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1))
    op.alter_column('products', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='마지막 수정 시각 (UPDATE 시 자동 갱신)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('products', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='레코드 최초 생성 시각 (UTC, DB 기본값으로 자동 채움)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('products', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='노출 상태. 목록 API 는 ACTIVE 만 조회',
               existing_nullable=False)
    op.alter_column('products', 'stock',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='재고 수량. 보통 1개씩이지만 동일 모델 다수 입고 가능',
               existing_nullable=False)
    op.alter_column('products', 'height_cm',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='높이 (cm)',
               existing_nullable=True)
    op.alter_column('products', 'depth_cm',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='깊이 (cm)',
               existing_nullable=True)
    op.alter_column('products', 'width_cm',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='가로 (cm)',
               existing_nullable=True)
    op.alter_column('products', 'weight_kg',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='제품 무게(kg). 누적 절약 무게 집계와 배송비 산정에 사용',
               existing_nullable=True)
    op.alter_column('products', 'original_price',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='원가/정가 (원). 할인율 계산 기준 — NULL 이면 할인 표기 생략',
               existing_nullable=True)
    op.alter_column('products', 'price',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='판매가 (원). 통화는 KRW 고정',
               existing_nullable=False)
    op.alter_column('products', 'warranty_works',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment="동작 보증 여부. true 면 카드/상세에 '동작보증' 뱃지 노출",
               existing_nullable=False)
    op.alter_column('products', 'condition_grade',
               existing_type=sa.VARCHAR(length=5),
               comment=None,
               existing_comment='상태 등급 A/B/C. 등급별 컬러 뱃지로 시각화',
               existing_nullable=False)
    op.alter_column('products', 'year_estimate',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='추정 연식 (yyyy). 철거 가전 특성상 정확한 제조연도가 없어 추정값',
               existing_nullable=True)
    op.alter_column('products', 'model_name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='모델명 (RT38K5982SL 등). 검색/AS 식별용',
               existing_nullable=True)
    op.alter_column('products', 'brand',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='브랜드명 (삼성/LG 등). 카드의 메타라인에 노출',
               existing_nullable=True)
    op.alter_column('products', 'category',
               existing_type=sa.VARCHAR(length=30),
               comment=None,
               existing_comment='대분류. 카테고리 칩 필터링과 인덱스 검색에 사용',
               existing_nullable=False)
    op.alter_column('products', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='상세 설명 (플레인 텍스트). 마크다운/HTML 은 서비스 레이어에서 sanitize',
               existing_nullable=False)
    op.alter_column('products', 'title',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='상품명. 카드/검색 노출용 — 브랜드+모델+용량 포함 권장',
               existing_nullable=False)
    op.alter_column('products', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='상품 PK',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1))
    op.alter_column('product_images', 'label',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='이미지 라벨 (정면/측면/흠집 등). NULL 허용이지만 등급 B/C 는 흠집 권장',
               existing_nullable=True)
    op.alter_column('product_images', 'sort_order',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='갤러리 정렬 순서 (0 부터 오름차순). 0 번이 카드 썸네일',
               existing_nullable=False)
    op.alter_column('product_images', 'url',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='S3 객체 URL (uploads/confirm 통과한 키만 허용)',
               existing_nullable=False)
    op.alter_column('product_images', 'product_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='소유 상품 FK (상품 삭제 시 cascade)',
               existing_nullable=False)
    op.alter_column('product_images', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='이미지 PK',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1))
    op.alter_column('payments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='마지막 수정 시각 (UPDATE 시 자동 갱신)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('payments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='레코드 최초 생성 시각 (UTC, DB 기본값으로 자동 채움)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('payments', 'approval_number',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='카드 승인번호. 환불/취소 호출 시 PG 가 요구',
               existing_nullable=True)
    op.alter_column('payments', 'installment_months',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='할부 개월 (0=일시불, 2~12=할부)',
               existing_nullable=True)
    op.alter_column('payments', 'card_last4',
               existing_type=sa.VARCHAR(length=4),
               comment=None,
               existing_comment='카드 끝 4자리. PCI-DSS 가 명시 허용 (first6+last4 까지 OK)',
               existing_nullable=True)
    op.alter_column('payments', 'card_company',
               existing_type=sa.VARCHAR(length=30),
               comment=None,
               existing_comment="카드 발급사 (예: '신한카드'). 영수증 표시용 — PCI-DSS 안전",
               existing_nullable=True)
    op.alter_column('payments', 'fail_reason',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='실패 사유 (PG 에러 메시지). 사용자 노출 전 정제 필요',
               existing_nullable=True)
    op.alter_column('payments', 'cancelled_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='취소/환불 시각',
               existing_nullable=True)
    op.alter_column('payments', 'paid_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='PG 승인 시각',
               existing_nullable=True)
    op.alter_column('payments', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='결제 상태. webhook 처리의 멱등성 기준',
               existing_nullable=False)
    op.alter_column('payments', 'amount',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='결제 금액(원). Order.total_amount 와 일치해야 함',
               existing_nullable=False)
    op.alter_column('payments', 'method',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='결제 수단 (CARD/BANK/KAKAO_PAY/NAVER_PAY/TOSS_PAY)',
               existing_nullable=False)
    op.alter_column('payments', 'pg_tid',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='PG 거래 ID. 멱등성 키 — webhook 중복 호출 방어용 unique 제약',
               existing_nullable=True)
    op.alter_column('payments', 'pg_provider',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='결제 PG (TOSS/KAKAO/NAVER)',
               existing_nullable=False)
    op.alter_column('payments', 'order_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='결제 대상 주문 FK. 결제가 있는 주문은 삭제 차단',
               existing_nullable=False)
    op.alter_column('payments', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='결제 PK',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1))
    op.alter_column('orders', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='마지막 수정 시각 (UPDATE 시 자동 갱신)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='레코드 최초 생성 시각 (UTC, DB 기본값으로 자동 채움)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('orders', 'cancelled_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='취소 시각. CANCELLED/REFUNDED 전환 시 채움',
               existing_nullable=True)
    op.alter_column('orders', 'paid_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='결제 완료 시각. PAID 전환 시 채움',
               existing_nullable=True)
    op.alter_column('orders', 'memo',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='배송 메모 (예: 부재 시 경비실)',
               existing_nullable=True)
    op.alter_column('orders', 'address2',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='상세 주소 (스냅샷)',
               existing_nullable=True)
    op.alter_column('orders', 'address1',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='기본 주소 (스냅샷)',
               existing_nullable=False)
    op.alter_column('orders', 'zipcode',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='우편번호 (스냅샷)',
               existing_nullable=False)
    op.alter_column('orders', 'recipient_phone',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='수령인 연락처 (스냅샷)',
               existing_nullable=False)
    op.alter_column('orders', 'recipient_name',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='수령인 이름 (스냅샷)',
               existing_nullable=False)
    op.alter_column('orders', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='주문 상태. 관리자 탭 카운트와 사용자 마이페이지 카운트의 기준',
               existing_nullable=False)
    op.alter_column('orders', 'shipping_method',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='배송 방식. DIRECT 는 zipcode 가 서울/경기 prefix 일 때만 허용',
               existing_nullable=False)
    op.alter_column('orders', 'discount_amount',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='할인 금액(원). 직배송 선택 시 -20,000 등',
               existing_nullable=False)
    op.alter_column('orders', 'shipping_fee',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='배송비(원). 화물 60,000 / 직배송 40,000 / 일반택배는 무게 기반',
               existing_nullable=False)
    op.alter_column('orders', 'total_amount',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='최종 결제 금액(원) = 상품합 + 배송비 - 할인',
               existing_nullable=False)
    op.alter_column('orders', 'user_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='주문자 FK. 거래 정보 보존(5년) 의무로 RESTRICT — 회원 탈퇴 시에도 주문은 남김',
               existing_nullable=False)
    op.alter_column('orders', 'order_number',
               existing_type=sa.VARCHAR(length=32),
               comment=None,
               existing_comment='사람이 읽는 주문번호 (RK-YYMMDD####). 영수증/CS 식별자',
               existing_nullable=False)
    op.alter_column('orders', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='주문 PK (내부용)',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1))
    op.alter_column('order_items', 'quantity',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='주문 수량',
               existing_nullable=False)
    op.alter_column('order_items', 'price_snapshot',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='주문 당시 판매가 (스냅샷). 가격 변동 후에도 결제 금액 재현 가능',
               existing_nullable=False)
    op.alter_column('order_items', 'product_image_url_snapshot',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='주문 당시 대표 이미지 URL (스냅샷). 주문내역/마이페이지 카드에 노출',
               existing_nullable=True)
    op.alter_column('order_items', 'product_title_snapshot',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='주문 당시 상품명 (스냅샷)',
               existing_nullable=False)
    op.alter_column('order_items', 'product_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='원본 상품 FK. RESTRICT — 주문이 있는 상품은 삭제 차단',
               existing_nullable=False)
    op.alter_column('order_items', 'order_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='소속 주문 FK',
               existing_nullable=False)
    op.alter_column('order_items', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='주문 라인 PK',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1))
    op.alter_column('identity_verifications', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='마지막 수정 시각 (UPDATE 시 자동 갱신)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('identity_verifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='레코드 최초 생성 시각 (UTC, DB 기본값으로 자동 채움)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('identity_verifications', 'fail_reason',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='FAIL 사유 (PG 에러 메시지). 사용자 노출 전 정제 필요',
               existing_nullable=True)
    op.alter_column('identity_verifications', 'verified_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='SUCCESS 시점. FAIL 이면 NULL',
               existing_nullable=True)
    op.alter_column('identity_verifications', 'request_id',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='PG 요청 식별자. 콜백 멱등성 보장 키 — 유니크 인덱스 추가 검토',
               existing_nullable=True)
    op.alter_column('identity_verifications', 'result',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='인증 결과 (SUCCESS/FAIL)',
               existing_nullable=False)
    op.alter_column('identity_verifications', 'provider',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='인증 PG (TOSS/NICE/KCB)',
               existing_nullable=False)
    op.alter_column('identity_verifications', 'user_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='인증 시도 사용자 FK',
               existing_nullable=False)
    op.alter_column('identity_verifications', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='인증 시도 PK',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1))
    op.alter_column('cart_items', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='마지막 수정 시각 (UPDATE 시 자동 갱신)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('cart_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='레코드 최초 생성 시각 (UTC, DB 기본값으로 자동 채움)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('cart_items', 'quantity',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='수량. 가전은 보통 1 이지만 동일 모델 다수 담기 허용',
               existing_nullable=False)
    op.alter_column('cart_items', 'product_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='담긴 상품 FK. 상품 삭제 시 cascade 로 함께 제거',
               existing_nullable=False)
    op.alter_column('cart_items', 'user_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='소유 사용자 FK. 탈퇴 시 cascade 정리',
               existing_nullable=False)
    op.alter_column('cart_items', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='장바구니 항목 PK',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1))
    op.alter_column('addresses', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='마지막 수정 시각 (UPDATE 시 자동 갱신)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('addresses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='레코드 최초 생성 시각 (UTC, DB 기본값으로 자동 채움)',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('addresses', 'is_default',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='기본 배송지 여부 — 사용자별 1건만 true 가 되도록 서비스 레이어에서 보장',
               existing_nullable=False)
    op.alter_column('addresses', 'address2',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='상세 주소 (동·호수 등)',
               existing_nullable=True)
    op.alter_column('addresses', 'address1',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='기본 주소 (도로명/지번)',
               existing_nullable=False)
    op.alter_column('addresses', 'zipcode',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='우편번호 5자리 (직배송 가능 지역 판정에 사용)',
               existing_nullable=False)
    op.alter_column('addresses', 'phone',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='수령인 연락처 (배송 안내용)',
               existing_nullable=False)
    op.alter_column('addresses', 'recipient',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='수령인 이름',
               existing_nullable=False)
    op.alter_column('addresses', 'user_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='소유 사용자 FK (회원 탈퇴 시 cascade 삭제)',
               existing_nullable=False)
    op.alter_column('addresses', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='배송지 PK',
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1))
    op.drop_table('favorites')
    # ### end Alembic commands ###
