"""add_product_brand_snapshot_to_order_items

Revision ID: ee1a45f3a6b2
Revises: d958aba2670e
Create Date: 2026-07-01 09:20:31.211000+09:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ee1a45f3a6b2'
down_revision: Union[str, None] = 'd958aba2670e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('product_brand_snapshot', sa.String(length=100), nullable=True, comment='주문 당시 브랜드명 (스냅샷). NULL 허용 — 브랜드 미입력 상품 대응'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'product_brand_snapshot')
    # ### end Alembic commands ###
