"""add answer_content to contacts

Revision ID: f25b27344175
Revises: 9855aeca0293
Create Date: 2026-07-04 12:42:56.511140+09:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f25b27344175'
down_revision: Union[str, None] = '9855aeca0293'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('answer_content', sa.Text(), nullable=True, comment='관리자 답변 내용'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'answer_content')
    # ### end Alembic commands ###
